// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKU3DwjYQCGFlFDAuSADXTCX3qev2xzY',
    appId: '1:929182075502:web:7bf2e6ff61b230828bf47f',
    messagingSenderId: '929182075502',
    projectId: 'companyapp-e3ba0',
    authDomain: 'companyapp-e3ba0.firebaseapp.com',
    storageBucket: 'companyapp-e3ba0.appspot.com',
    measurementId: 'G-6G9T9R0FPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoJtV4NuvRerS7W38BtHhHNBEnDkfIKig',
    appId: '1:929182075502:android:2eed2c2383e488238bf47f',
    messagingSenderId: '929182075502',
    projectId: 'companyapp-e3ba0',
    storageBucket: 'companyapp-e3ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDEzY0UuOL2nCxwkdrD-Ys6Maz9F-XOyw',
    appId: '1:929182075502:ios:529fd56ba3a4cfb28bf47f',
    messagingSenderId: '929182075502',
    projectId: 'companyapp-e3ba0',
    storageBucket: 'companyapp-e3ba0.appspot.com',
    iosBundleId: 'com.example.KingStarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDEzY0UuOL2nCxwkdrD-Ys6Maz9F-XOyw',
    appId: '1:929182075502:ios:529fd56ba3a4cfb28bf47f',
    messagingSenderId: '929182075502',
    projectId: 'companyapp-e3ba0',
    storageBucket: 'companyapp-e3ba0.appspot.com',
    iosBundleId: 'com.example.KingStarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQKU3DwjYQCGFlFDAuSADXTCX3qev2xzY',
    appId: '1:929182075502:web:aab7e8ee2f00cd9a8bf47f',
    messagingSenderId: '929182075502',
    projectId: 'companyapp-e3ba0',
    authDomain: 'companyapp-e3ba0.firebaseapp.com',
    storageBucket: 'companyapp-e3ba0.appspot.com',
    measurementId: 'G-H5B6SN5RWB',
  );

}